[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
minify = "on_release"

[watch]
watch = [
    "src",
    "js-out",
    "style",
    "near-min-api/src",
    "public",
    "Cargo.toml",
    ".env",
    "index.html"
]
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false
headers = { "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Methods" = "*" }
