/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_pubkey_free: (a: number, b: number) => void;
export const pubkey_constructor: (a: any) => [number, number, number];
export const pubkey_equals: (a: number, b: number) => number;
export const pubkey_toBytes: (a: number) => [number, number];
export const pubkey_toString: (a: number) => [number, number];
export const rustsecp256k1_v0_8_1_context_create: (a: number) => number;
export const rustsecp256k1_v0_8_1_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_8_1_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_8_1_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure11620_externref_shim: (a: number, b: number, c: any) => void;
export const closure2625_externref_shim: (a: number, b: number, c: any) => void;
export const closure2624_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const closure11716_externref_shim: (a: number, b: number, c: any) => void;
export const closure10918_externref_shim: (a: number, b: number, c: any) => void;
export const closure11795_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen_b534d88c1f38e9e7___convert__closures_____invoke______: (a: number, b: number) => void;
export const wasm_bindgen_b534d88c1f38e9e7___convert__closures_____invoke______16: (a: number, b: number) => void;
export const closure10878_externref_shim: (a: number, b: number, c: any) => void;
export const closure2623_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen_b534d88c1f38e9e7___convert__closures_____invoke______19: (a: number, b: number) => void;
export const wasm_bindgen_b534d88c1f38e9e7___convert__closures_____invoke______20: (a: number, b: number) => void;
export const closure11811_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
