/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___wasm_bindgen_f089307a9adbbdd1___JsValue__core_de11c6d026cca4da___result__Result_____wasm_bindgen_f089307a9adbbdd1___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___js_sys_34ec583cdf7e34d9___Array__web_sys_3e65c5dd2e1844f1___features__gen_IntersectionObserver__IntersectionObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___js_sys_34ec583cdf7e34d9___Function_fn_wasm_bindgen_f089307a9adbbdd1___JsValue_____wasm_bindgen_f089307a9adbbdd1___sys__Undefined___js_sys_34ec583cdf7e34d9___Function_fn_wasm_bindgen_f089307a9adbbdd1___JsValue_____wasm_bindgen_f089307a9adbbdd1___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___wasm_bindgen_f089307a9adbbdd1___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_UiEvent__UiEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_CloseEvent__CloseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___wasm_bindgen_f089307a9adbbdd1___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_WheelEvent__WheelEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_WheelEvent__WheelEvent______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_CloseEvent__CloseEvent______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_MessageEvent__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_UiEvent__UiEvent______true__11: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_MessageEvent__MessageEvent______true__12: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_UiEvent__UiEvent______true__13: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_UiEvent__UiEvent______true__14: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke___web_sys_3e65c5dd2e1844f1___features__gen_WheelEvent__WheelEvent______true__15: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke_______true__2_: (a: number, b: number) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke_______true__3_: (a: number, b: number) => void;
export const wasm_bindgen_f089307a9adbbdd1___convert__closures_____invoke_______true__4_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
