name: Deploy to dist branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.prod .env

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install build tools
        run: cargo install patch-crate cargo-dylint dylint-link --debug --locked

      - name: Install cargo-leptos from git
        run: cargo install cargo-leptos --git https://github.com/Sliman4/cargo-leptos-temp-fix --branch main --debug --locked

      - name: Install npm dependencies
        run: npm install

      - name: Install Tailwind CLI
        run: npm install -g @tailwindcss/cli@4.1.8

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Apply patches
        run: cargo patch-crate

      - name: Build JavaScript bundle
        run: npm run js:build

      - name: Lint with clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Lint with dylint
        run: cargo dylint --all

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: npm run build

      - name: Copy artifacts
        run: cp -r target/site/ dist/

      - name: Set PWA cache version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/{{{VERSION}}}/$COMMIT_HASH/g" dist/service_worker.js

      - name: Set Posthog API key
        # it's public
        run: |
          sed -i "s/{{{POSTHOG_API_KEY}}}/phc_GqwXPBXc21Vg3guG1pqkm51HGIVERCmloAI7PcxCRaC/g" dist/js/index.js

      - name: Create _redirects file
        run: echo "/*   /index.html   200" > dist/_redirects

      - name: Create netlify.toml file
        run: |
          cat > dist/netlify.toml << 'EOL'
          [[headers]]
            for = "/*"
            [headers.values]
              Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
              Access-Control-Allow-Origin = "*"
              Access-Control-Allow-Methods = "GET"
              Access-Control-Max-Age = "86400"

          [[headers]]
            for = "*.wasm"
            [headers.values]
              Cache-Control = "public, max-age=31536000, immutable"
              Content-Type = "application/wasm"
          EOL

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
