name: Deploy to dist branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .env file
        run: cp .env.prod .env
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install Trunk
        if: steps.cache-trunk.outputs.cache-hit != 'true'
        run: cargo install trunk
      
      - name: Install Tailwind CLI
        run: npm install tailwindcss@4.1.3 @tailwindcss/cli@4.1.3 && npm install -g @tailwindcss/cli@4.1.3
      
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Build with Trunk
        run: trunk build --release
      
      - name: Create _redirects file
        run: echo "/*   /index.html   200" > dist/_redirects
      
      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
