name: Deploy to dist branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.prod .env

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-04-19
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install patch-crate
        run: cargo binstall patch-crate

      - name: Install dylint
        run: cargo binstall cargo-dylint dylint-link

      - name: Install Trunk
        run: cargo binstall trunk

      - name: Install npm dependencies
        run: npm install

      - name: Install Tailwind CLI
        run: npm install -g @tailwindcss/cli@4.1.8

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Apply patches
        run: cargo patch-crate

      - name: Build JavaScript bundle
        run: npm run js:build

      - name: Lint with clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Lint with dylint
        run: cargo dylint --all

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: npm run build

      - name: Set PWA cache version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/{{{VERSION}}}/$COMMIT_HASH/g" dist/service_worker.js

      - name: Create _redirects file
        run: echo "/*   /index.html   200" > dist/_redirects

      - name: Create netlify.toml file
        run: |
          cat > dist/netlify.toml << 'EOL'
          [[headers]]
            for = "/*"
            [headers.values]
              Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
          EOL

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
