name: Deploy to dist branch

on:
  push:
    branches: [ main ]  # Change this to your default branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install Trunk
        run: cargo install trunk
      
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Build with Trunk
        run: trunk build --release
      
      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
