name: Deploy to dist branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.prod .env

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install patch-crate
        run: cargo install patch-crate

      - name: Apply patches
        run: cargo patch-crate

      - name: Install Trunk
        run: cargo install trunk

      - name: Install npm dependencies
        run: npm install

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Build JavaScript bundle
        run: npm run js:build

      - name: Build with Trunk
        run: trunk build --release --minify

      - name: Set PWA cache version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/{{{VERSION}}}/$COMMIT_HASH/g" dist/service_worker.js

      - name: Create _redirects file
        run: echo "/*   /index.html   200" > dist/_redirects

      - name: Create netlify.toml file
        run: |
          cat > dist/netlify.toml << 'EOL'
          [[headers]]
            for = "/*"
            [headers.values]
              Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
          EOL

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
